name: Hello world
on:
   pull_request:
   
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "[+] user.login: ${{github.event.pull_request.user.login}}"
         echo "[+] github.actor: ${{github.actor}}"
